### ISSUE TITLE
Wrong vars on README.md

### ISSUE THREAD

**Issue by LeonardoCardoso** [Nike-Inc/Elevate#17]
On this section [Using Multiple Decoders](https://github.com/Nike-Inc/Elevate#using-multiple-decoders), the var `json` is not declared:

Instead `Parser.parseEntity(json: json)` shouldn't it be `Parser.parseEntity(json: object)`?

**Comment by cnoon** [comment]
Thanks for reporting @LeonardoCardoso. I've just put up #20 which addresses this issue. I'm going to close this issue out for now. Please direct all further comments to #20.

Cheers. 🍻
