### ISSUE TITLE
Wrong version on README.md

### ISSUE THREAD

**Issue by LeonardoCardoso** [Nike-Inc/Elevate#2]
On the section [Installation](https://github.com/Nike-Inc/Elevate#installation), both CocoaPods and Carthage have version **1.0**, while the right version is **1.0.0**.

```ruby
pod 'Elevate', '~> 1.0'
```
```bash
github "Nike-Inc/Elevate" ~> 1.0
```

On CocoaPods, this will cause the error:
```
[!] Unable to find a specification for `Elevate (~> 1.0)`
```

**Comment by LeonardoCardoso** [comment]
Closing this issue.
This won't happen in the new versions of CocoaPods. 

Additionally, I had to run ```pod update```.

**Comment by cnoon** [comment]
The versioning is correct @LeonardoCardoso. The `~> 1.0` means everything including and above `1.0.0` but less than `2.x`. For more info, please check out the CocoaPods [versioning](https://guides.cocoapods.org/syntax/podfile.html#pod) docs.
